# Hesitation analysis nb
Nb for testing out somr functions and other stuff for hesitation analysis

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pickle

In [ ]:
def normalizeGaps(gaps):
    """Normalize all gaps ts in list to occur in t=[0,1]. Will use minmax normal

    Args:
        gaps (array): Array of gaps (x,y,z,t)
        coord_ind (int): Index of relevant coord (default is 2/z)
    """
    t_list = []
    t_min = -np.inf
    t_max = np.inf
    for gap in gaps:
        t_list = gap[:,-1]
    t_min = np.min(t_list)
    t_max = np.min(t_list)
    gaps_norm_t = (t_list - t_min)/(t_max-t_min)
    gaps_norm = gaps.copy()
    gaps_norm[:,:,-1] = gaps_norm_t

    return gaps_norm
    

def plotGapHeat(gaps,color_ind=2):
    """Plot heat maps of gaps, one gap per row could be normal

    Args:
        gaps (array): Array of gaps (x,y,z,t) 
        coord_ind (int): Index of relevant coord (default is 2/z)
    """
    # Convert to NumPy array for easier manipulation
    gaps = np.array(gaps, dtype=float)  # Shape: (num_gaps, num_points, 4)
    
    # Determine which index to use for coloring
    
    # Extract values for heatmap
    color_values = gaps[:, :, color_ind]  # Extract chosen variable
    
    # Plot the heatmap
    plt.figure(figsize=(10, len(gaps)))  # Adjust height based on number of gaps
    plt.imshow(color_values, aspect='auto', cmap='viridis', interpolation='nearest')

    # Label axes
    plt.xlabel("Normalized Time (t)")
    plt.ylabel("Gap Index")
    plt.colorbar()
    
    plt.show()

In [ ]:
dat_dir = '/Users/dan/freiwaldDrive/dhanuska/hand_track/Pancho/231114_grampancho1/processed_data.pkl'
with open(dat_dir,'rb') as f:
    dat_in = pickle.load(f)

In [11]:
dat = {}
for trial in dat_in.keys():
    if '220914_flea_bfs1_dlc' in dat_in[trial].keys():
        dat[trial] = dat_in[trial]['220914_flea_bfs1_dlc']

In [13]:
print(dat[10].keys())

dict_keys(['strokes_cam', 'gaps_cam', 'pts_time_cam_all', 'strokes_touch', 'strokes_task', 'pnut_strokes', 'reg_strokes_cam', 'reg_gaps_cam', 'reg_pts_time_cam_all', 'trans_strokes_cam', 'trans_gaps_cam', 'trans_pts_time_cam_all'])


In [43]:
gaps = []
for trial,d in dat.items():
    if len(d) != 0:
        for gap in d['trans_gaps_cam']:
            gaps.append(np.array(gap))


[[-0.05223593 -0.24405287  0.12953737  0.396     ]
 [-0.05215761 -0.24399269  0.1294456   0.41605892]
 [-0.05221689 -0.24405441  0.1294776   0.43611784]
 [-0.05224802 -0.24398424  0.12948134  0.45617676]
 [-0.05070893 -0.24120952  0.12865411  0.47623568]
 [-0.04961484 -0.24003198  0.12743176  0.4962946 ]
 [-0.04957976 -0.24008773  0.12743032  0.51635352]
 [-0.04947925 -0.2402381   0.12740305  0.53641244]
 [-0.05087384 -0.24273155  0.12925874  0.55647136]
 [-0.05083649 -0.2428103   0.12925563  0.57653028]
 [-0.05080746 -0.24281554  0.12925897  0.5965892 ]
 [-0.05079869 -0.24283645  0.12925982  0.61664812]
 [-0.05069813 -0.24272342  0.12914158  0.63670704]
 [-0.05093595 -0.24310876  0.12927113  0.65676596]
 [-0.05077033 -0.24284496  0.12916783  0.67682488]
 [-0.05077033 -0.24284496  0.12916783  0.6968838 ]
 [-0.05071351 -0.24267771  0.12909174  0.71694272]
 [-0.0507174  -0.24265671  0.12908933  0.73700164]
 [-0.05068541 -0.24261948  0.12906053  0.75706056]
 [-0.05069874 -0.24253891  0.12

In [26]:
gaps_norm = normalizeGaps(gaps)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed